version: '3'
services:
  app:
    container_name: splainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/splainer
    ports:
      - 5173:5173
    command: ['yarn', 'dev', '--host', '0.0.0.0', '--port', '5173']
