name: Java CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set release version Name
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          MAVEN_OPTS: -Dtest.solr.allowed.securerandom=NativePRNG
      - name: Stage jar
        run: cp solr-splainer-package/target/*.jar solr-splainer-package/target/solr-splainer-${{ env.RELEASE_VERSION }}.jar
      - name: Create and Upload Release
        id: create_and_upload_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          files: ./solr-splainer-package/target/solr-splainer-${{ env.RELEASE_VERSION }}.jar

